services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: login
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  login-app:
    build: .
    container_name: login_container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0smrhidbo4c73f871n0-a.oregon-postgres.render.com:5432/login_0fm2
      SPRING_DATASOURCE_USERNAME: login_0fm2_user
      SPRING_DATASOURCE_PASSWORD: 5X8TN66MGPY2lYFhmEm6W3KT2I5s1Pls
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - login-app

volumes:
  pgdata: