services:
  - type: web
    name: fullstack-login-app
    env: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    autoDeploy: true

databases:
  - name: postgres-login
    plan: free
    region: oregon
    databaseName: login_0fm2
    user: login_0fm2_user
