services:
  - type: web
    name: springboot-login-api
    env: java
    buildCommand: echo "➡️ JAVA_HOME is $JAVA_HOME" && java -version && ./gradlew build
    startCommand: java -jar build/libs/*.jar
    autoDeploy: true
    plan: free