services:
  - type: web
    name: aavc
    env: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - fromDatabase:
          name: postgres-login       # ✅ match the DB service name below
          property: host
          envVarKey: SPRING_DATASOURCE_HOST
      - fromDatabase:
          name: postgres-login
          property: user
          envVarKey: SPRING_DATASOURCE_USERNAME
      - fromDatabase:
          name: postgres-login
          property: password
          envVarKey: SPRING_DATASOURCE_PASSWORD
      - fromDatabase:
          name: postgres-login
          property: database
          envVarKey: SPRING_DATASOURCE_DATABASE
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:5432/${SPRING_DATASOURCE_DATABASE}

databases:
  - name: postgres-login         # ✅ Must match references above
    plan: free
    region: oregon
    databaseName: login_0fm2
    user: login_0fm2_user