services:
  - type: web
    name: aavc
    env: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: SPRING_DATASOURCE_HOST
        fromDatabaseId: postgres-login
        property: host

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabaseId: postgres-login
        property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabaseId: postgres-login
        property: password

      - key: SPRING_DATASOURCE_DATABASE
        fromDatabaseId: postgres-login
        property: database

      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://login_0fm2_user:5X8TN66MGPY2lYFhmEm6W3KT2I5s1Pls@dpg-d0smrhidbo4c73f871n0-a/login_0fm2

databases:
  - name: postgres-login
    plan: free
    region: oregon
    databaseName: login_0fm2
    user: login_0fm2_user