services:
  - type: web
    name: aavc
    env: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - fromDatabase:
          name: postgres-login       # ✅ match the DB service name below
          property: host
          envVarKey: dpg-d0smrhidbo4c73f871n0-a
      - fromDatabase:
          name: postgres-login
          property: user
          envVarKey: login_0fm2_user
      - fromDatabase:
          name: postgres-login
          property: password
          envVarKey: 5X8TN66MGPY2lYFhmEm6W3KT2I5s1Pls
      - fromDatabase:
          name: postgres-login
          property: database
          envVarKey: login_0fm2
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:5432/${SPRING_DATASOURCE_DATABASE}

databases:
  - name: postgres-login         # ✅ Must match references above
    plan: free
    region: oregon
    databaseName: login_0fm2
    user: login_0fm2_user