spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: login
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 996128408853-jpm0meppt5r98rk61ri0dr8j73dlumj6.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG