spring:
  application:
    name: login
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
     hibernate:
      ddl-auto: update
     show-sql: true
     properties:
          hibernate:
           dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
      org.springframework.security: DEBUG
